// 전체 테이블 삭제 쿼리문 소환
SELECT 'DROP TABLE "'||TABLE_NAME||'" CASCADE CONSTRAINTS;' FROM user_tables;

DROP TABLE "ACCOUNTS" CASCADE CONSTRAINTS;
DROP TABLE "PHOTOS" CASCADE CONSTRAINTS;
DROP TABLE "BOARDS" CASCADE CONSTRAINTS;
DROP TABLE "MEETINGS" CASCADE CONSTRAINTS;
DROP TABLE "MEETING_ATTENDEES" CASCADE CONSTRAINTS;
DROP TABLE "COMMENTS" CASCADE CONSTRAINTS;
DROP TABLE "FAVORITES" CASCADE CONSTRAINTS;
DROP TABLE "GOODS" CASCADE CONSTRAINTS;


// 전체 시퀀스 삭제 쿼리문 소환
SELECT 'DROP sequence "'||SEQUENCE_NAME||'";' FROM user_sequences;
DROP sequence "BOARDS_SEQ";
DROP sequence "FAVORITES_SEQ";
DROP sequence "GOODS_SEQ";